# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is deprecated now (default is chaching_sha2_password)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: N0tm34nt4Pr0ducti0n!
    ports:
      - "3306:3306"
